In [1]:
import numpy as np

In [2]:
array_hw=np.array([[5,5,8,8,9,8],[7,7,5,3,5,7],[8,7,8,4,2,6],[9,9,7,3,1,4]])

In [13]:
print (array_hw)

[[5 5 8 8 9 8]
 [7 7 5 3 5 7]
 [8 7 8 4 2 6]
 [9 9 7 3 1 4]]


In [4]:
#1 Sort the flattened array

ar_flat = array_hw.flatten()
print (np.sort(ar_flat))

[1 2 3 3 4 4 5 5 5 5 6 7 7 7 7 7 8 8 8 8 8 9 9 9]


In [17]:
#2 Sort the second column
print (np.sort(array_hw, axis=0)[:,1])

[5 7 7 9]


In [18]:
#3 Sort the third row
print (np.sort(array_hw, axis=1)[2, :])

[2 4 6 7 8 8]


In [23]:
#4 Extract the second row onwards
print(array_hw[1:,:])

[[7 7 5 3 5 7]
 [8 7 8 4 2 6]
 [9 9 7 3 1 4]]


In [25]:
#5 Extract the third column onwards
print(array_hw[:,2:])

[[8 8 9 8]
 [5 3 5 7]
 [8 4 2 6]
 [7 3 1 4]]


In [26]:
#6 obtain the square of array_hw
print(np.square(array_hw))

[[25 25 64 64 81 64]
 [49 49 25  9 25 49]
 [64 49 64 16  4 36]
 [81 81 49  9  1 16]]


In [27]:
#7 Slice the element from the third row and fourth column position 3X4
print (array_hw[3,4])

1


In [28]:
#8  obtain the total sum of array_hw
print (np.sum(array_hw))

145


In [35]:
#9 How many dimentions does array_hw have
print ("Number of dimentions: ", (array_hw.ndim))

Number of dimentions:  2


In [37]:
#10 What is the data type listed in array_hw
print ("Datatype: ", (array_hw.dtype))

Datatype:  int64


In [39]:
#11 What is the size of the memory in bytes consumed by all the elements in array_hw?
print (array_hw.nbytes)

192
